# This file was generated by GoReleaser. DO NOT EDIT.
cask "plakar" do
  name "plakar"
  desc "Plakar is a secure backup solution for all your data sources, including filesystems, S3 buckets, Cloud resources, SFTP servers, and more."
  homepage "https://plakar.io/"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plakar"
  manpage "./man/plakar-cat.1"
  manpage "./man/plakar-ui.1"
  manpage "./man/plakar-locate.1"
  manpage "./man/plakar-diag.1"
  manpage "./man/plakar-archive.1"
  manpage "./man/plakar-source.1"
  manpage "./man/plakar-destination.1"
  manpage "./man/plakar-store.1"
  manpage "./man/plakar-digest.1"
  manpage "./man/plakar-scheduler.1"
  manpage "./man/plakar-diff.1"
  manpage "./man/plakar-server.1"
  manpage "./man/plakar-ptar.1"
  manpage "./man/plakar-agent.1"
  manpage "./man/plakar-dup.1"
  manpage "./man/plakar-info.1"
  manpage "./man/plakar-clone.1"
  manpage "./man/plakar-version.1"
  manpage "./man/plakar-mount.1"
  manpage "./man/plakar-maintenance.1"
  manpage "./man/plakar-prune.1"
  manpage "./man/plakar-ls.1"
  manpage "./man/plakar-sync.1"
  manpage "./man/plakar-service.1"
  manpage "./man/plakar-backup.1"
  manpage "./man/plakar-create.1"
  manpage "./man/plakar-restore.1"
  manpage "./man/plakar-check.1"
  manpage "./man/plakar-rm.1"
  manpage "./man/plakar-logout.1"
  manpage "./man/plakar-login.1"
  manpage "./man/plakar-token.1"
  manpage "./man/plakar-pkg-build.1"
  manpage "./man/plakar-pkg-add.1"
  manpage "./man/plakar-pkg-rm.1"
  manpage "./man/plakar-pkg-create.1"
  manpage "./man/plakar-pkg-show.1"
  manpage "./man/plakar-policy.1"
  manpage "./man/plakar.1"
  manpage "./man/plakar-query.7"
  manpage "./man/plakar-pkg-manifest.yaml.5"
  manpage "./man/plakar-pkg-recipe.yaml.5"

  on_macos do
    on_intel do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_darwin_amd64.tar.gz"
      sha256 "38649b2a1f2aa9cd97ffe97c8e7ae4b69069e12d6d78692adb54784e5d778a2d"
    end
    on_arm do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_darwin_arm64.tar.gz"
      sha256 "0141abbeada8d8698bcdde5fce7fccc6a6cd987d3bde8148b577e96d663874a1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_linux_amd64.tar.gz"
      sha256 "1fdbca9c63f02d28137739e1cae5d493bd81bd2d0182b3b5ac2fbb61f23fea4a"
    end
    on_arm do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_linux_arm64.tar.gz"
      sha256 "affad45bfac62238e386a601692f8051abe0757e514d2cdd7209fd48ffdb47d8"
    end
  end

  caveats do
    "Run plakar help to get started."
  end

  # No zap stanza required
end
