# This file was generated by GoReleaser. DO NOT EDIT.
cask "plakar" do
  name "plakar"
  desc "Plakar is a secure backup solution for all your data sources, including filesystems, S3 buckets, Cloud resources, SFTP servers, and more."
  homepage "https://plakar.io/"
  version "1.0.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plakar"
  manpage "./man/plakar-cat.1"
  manpage "./man/plakar-ui.1"
  manpage "./man/plakar-locate.1"
  manpage "./man/plakar-diag.1"
  manpage "./man/plakar-archive.1"
  manpage "./man/plakar-source.1"
  manpage "./man/plakar-destination.1"
  manpage "./man/plakar-store.1"
  manpage "./man/plakar-digest.1"
  manpage "./man/plakar-scheduler.1"
  manpage "./man/plakar-diff.1"
  manpage "./man/plakar-server.1"
  manpage "./man/plakar-ptar.1"
  manpage "./man/plakar-agent.1"
  manpage "./man/plakar-dup.1"
  manpage "./man/plakar-info.1"
  manpage "./man/plakar-clone.1"
  manpage "./man/plakar-version.1"
  manpage "./man/plakar-mount.1"
  manpage "./man/plakar-maintenance.1"
  manpage "./man/plakar-prune.1"
  manpage "./man/plakar-ls.1"
  manpage "./man/plakar-sync.1"
  manpage "./man/plakar-service.1"
  manpage "./man/plakar-backup.1"
  manpage "./man/plakar-create.1"
  manpage "./man/plakar-restore.1"
  manpage "./man/plakar-check.1"
  manpage "./man/plakar-rm.1"
  manpage "./man/plakar-logout.1"
  manpage "./man/plakar-login.1"
  manpage "./man/plakar-token.1"
  manpage "./man/plakar-pkg-build.1"
  manpage "./man/plakar-pkg-add.1"
  manpage "./man/plakar-pkg-rm.1"
  manpage "./man/plakar-pkg-create.1"
  manpage "./man/plakar-pkg-show.1"
  manpage "./man/plakar-policy.1"
  manpage "./man/plakar.1"
  manpage "./man/plakar-query.7"
  manpage "./man/plakar-pkg-manifest.yaml.5"
  manpage "./man/plakar-pkg-recipe.yaml.5"

  on_macos do
    on_intel do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_darwin_amd64.tar.gz"
      sha256 "6dec99d43436143d86d6d2afa25f7acc77e52c19a37a1f33a6385d3e71e96161"
    end
    on_arm do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_darwin_arm64.tar.gz"
      sha256 "3a5461d9601314c6d02f8662920edcc15320862aefb861ce0704077d34005eca"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_linux_amd64.tar.gz"
      sha256 "6bf8ca48821211827f59f0481d88ed7eab8d0a6bd046dc41d8a7657b43df2eb1"
    end
    on_arm do
      url "https://github.com/PlakarKorp/plakar/releases/download/v#{version}/plakar_#{version}_linux_arm64.tar.gz"
      sha256 "a09c1cb610e46acff3be43b2916587768dcfea18cc2c5715052c6582943c8ccf"
    end
  end

  caveats do
    "Run plakar help to get started."
  end

  # No zap stanza required
end
